# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

countries = [
    {"id": 33, "iso2": "AF", "iso3": "AFG", "name_pl": "Afganistan", "name_en": "Afghanistan", "prefix": "+93"},
    {"id": 34, "iso2": "AX", "iso3": "ALA", "name_pl": "Wyspy Alandzkie", "name_en": "Åland Islands", "prefix": "+358"},
    {"id": 35, "iso2": "AL", "iso3": "ALB", "name_pl": "Albania", "name_en": "Albania", "prefix": "+355"},
    {"id": 36, "iso2": "DZ", "iso3": "DZA", "name_pl": "Algieria", "name_en": "Algeria", "prefix": "+213"},
    {
        "id": 37,
        "iso2": "AS",
        "iso3": "ASM",
        "name_pl": "Samoa Amerykańskie",
        "name_en": "American Samoa",
        "prefix": "+1-684",
    },
    {"id": 38, "iso2": "AD", "iso3": "AND", "name_pl": "Andora", "name_en": "Andorra", "prefix": "+376"},
    {"id": 39, "iso2": "AO", "iso3": "AGO", "name_pl": "Angola", "name_en": "Angola", "prefix": "+244"},
    {"id": 40, "iso2": "AI", "iso3": "AIA", "name_pl": "Anguilla", "name_en": "Anguilla", "prefix": "+1-264"},
    {"id": 41, "iso2": "AQ", "iso3": "ATA", "name_pl": "Antarktyka", "name_en": "Antarctica", "prefix": ""},
    {
        "id": 42,
        "iso2": "AG",
        "iso3": "ATG",
        "name_pl": "Antigua i Barbuda",
        "name_en": "Antigua and Barbuda",
        "prefix": "+1-268",
    },
    {"id": 43, "iso2": "AR", "iso3": "ARG", "name_pl": "Argentyna", "name_en": "Argentina", "prefix": "+54"},
    {"id": 44, "iso2": "AM", "iso3": "ARM", "name_pl": "Armenia", "name_en": "Armenia", "prefix": "+374"},
    {"id": 45, "iso2": "AW", "iso3": "ABW", "name_pl": "Aruba", "name_en": "Aruba", "prefix": "+297"},
    {"id": 46, "iso2": "AU", "iso3": "AUS", "name_pl": "Australia", "name_en": "Australia", "prefix": "+61"},
    {"id": 20, "iso2": "AT", "iso3": "AUT", "name_pl": "Austria", "name_en": "Austria", "prefix": "+43"},
    {"id": 48, "iso2": "AZ", "iso3": "AZE", "name_pl": "Azerbejdżan", "name_en": "Azerbaijan", "prefix": "+994"},
    {"id": 49, "iso2": "BS", "iso3": "BHS", "name_pl": "Bahamy", "name_en": "Bahamas", "prefix": "+1-242"},
    {"id": 50, "iso2": "BH", "iso3": "BHR", "name_pl": "Bahrajn", "name_en": "Bahrain", "prefix": "+973"},
    {"id": 51, "iso2": "BD", "iso3": "BGD", "name_pl": "Bangladesz", "name_en": "Bangladesh", "prefix": "+880"},
    {"id": 52, "iso2": "BB", "iso3": "BRB", "name_pl": "Barbados", "name_en": "Barbados", "prefix": "+1-246"},
    {"id": 53, "iso2": "BY", "iso3": "BLR", "name_pl": "Białoruś", "name_en": "Belarus", "prefix": "+375"},
    {"id": 1, "iso2": "BE", "iso3": "BEL", "name_pl": "Belgia", "name_en": "Belgium", "prefix": "+32"},
    {"id": 55, "iso2": "BZ", "iso3": "BLZ", "name_pl": "Belize", "name_en": "Belize", "prefix": "+501"},
    {"id": 56, "iso2": "BJ", "iso3": "BEN", "name_pl": "Benin", "name_en": "Benin", "prefix": "+229"},
    {"id": 57, "iso2": "BM", "iso3": "BMU", "name_pl": "Bermudy", "name_en": "Bermuda", "prefix": "+1-441"},
    {"id": 58, "iso2": "BT", "iso3": "BTN", "name_pl": "Bhutan", "name_en": "Bhutan", "prefix": "+975"},
    {
        "id": 59,
        "iso2": "BO",
        "iso3": "BOL",
        "name_pl": "Boliwia",
        "name_en": "Bolivia (Plurinational State of)",
        "prefix": "+591",
    },
    {
        "id": 60,
        "iso2": "BQ",
        "iso3": "BES",
        "name_pl": "Bonaire, Sint Eustatius og Saba",
        "name_en": "Bonaire",
        "prefix": "+599",
    },
    {
        "id": 61,
        "iso2": "BA",
        "iso3": "BIH",
        "name_pl": "Bośnia i Hercegowina",
        "name_en": "Bosnia and Herzegovina",
        "prefix": "+387",
    },
    {"id": 62, "iso2": "BW", "iso3": "BWA", "name_pl": "Botswana", "name_en": "Botswana", "prefix": "+267"},
    {"id": 63, "iso2": "BV", "iso3": "BVT", "name_pl": "Wyspa Bouveta", "name_en": "Bouvet Island", "prefix": ""},
    {"id": 64, "iso2": "BR", "iso3": "BRA", "name_pl": "Brazylia", "name_en": "Brazil", "prefix": "+55"},
    {
        "id": 65,
        "iso2": "IO",
        "iso3": "IOT",
        "name_pl": "Brytyjskie Terytorium Oceanu Indyjskiego",
        "name_en": "British Indian Ocean Territory",
        "prefix": "",
    },
    {"id": 66, "iso2": "BN", "iso3": "BRN", "name_pl": "Brunei", "name_en": "Brunei Darussalam", "prefix": "+673"},
    {"id": 2, "iso2": "BG", "iso3": "BGR", "name_pl": "Bułgaria", "name_en": "Bulgaria", "prefix": "+359"},
    {"id": 68, "iso2": "BF", "iso3": "BFA", "name_pl": "Burkina Faso", "name_en": "Burkina Faso", "prefix": "+226"},
    {"id": 69, "iso2": "BI", "iso3": "BDI", "name_pl": "Burundi", "name_en": "Burundi", "prefix": "+257"},
    {"id": 70, "iso2": "KH", "iso3": "KHM", "name_pl": "Kambodża", "name_en": "Cambodia", "prefix": "+855"},
    {"id": 71, "iso2": "CM", "iso3": "CMR", "name_pl": "Kamerun", "name_en": "Cameroon", "prefix": "+237"},
    {"id": 72, "iso2": "CA", "iso3": "CAN", "name_pl": "Kanada", "name_en": "Canada", "prefix": "+1"},
    {
        "id": 73,
        "iso2": "CV",
        "iso3": "CPV",
        "name_pl": "Republika Zielonego Przylądka",
        "name_en": "Cabo Verde",
        "prefix": "+238",
    },
    {"id": 74, "iso2": "KY", "iso3": "CYM", "name_pl": "Kajmany", "name_en": "Cayman Islands", "prefix": "+1-345"},
    {
        "id": 75,
        "iso2": "CF",
        "iso3": "CAF",
        "name_pl": "Republika Środkowoafrykańska",
        "name_en": "Central African Republic",
        "prefix": "+236",
    },
    {"id": 76, "iso2": "TD", "iso3": "TCD", "name_pl": "Czad", "name_en": "Chad", "prefix": "+235"},
    {"id": 77, "iso2": "CL", "iso3": "CHL", "name_pl": "Chile", "name_en": "Chile", "prefix": "+56"},
    {"id": 78, "iso2": "CN", "iso3": "CHN", "name_pl": "Chiny", "name_en": "China", "prefix": "+86"},
    {
        "id": 79,
        "iso2": "CX",
        "iso3": "CXR",
        "name_pl": "Wyspa Bożego Narodzenia",
        "name_en": "Christmas Island",
        "prefix": "+61",
    },
    {
        "id": 80,
        "iso2": "CC",
        "iso3": "CCK",
        "name_pl": "Wyspy Kokosowe",
        "name_en": "Cocos (Keeling) Islands",
        "prefix": "+61",
    },
    {"id": 81, "iso2": "CO", "iso3": "COL", "name_pl": "Kolumbia", "name_en": "Colombia", "prefix": "+57"},
    {"id": 82, "iso2": "KM", "iso3": "COM", "name_pl": "Komory", "name_en": "Comoros", "prefix": "+269"},
    {"id": 83, "iso2": "CG", "iso3": "COG", "name_pl": "Kongo", "name_en": "Congo", "prefix": "+242"},
    {
        "id": 84,
        "iso2": "CD",
        "iso3": "COD",
        "name_pl": "Demokratyczna Republika Konga",
        "name_en": "Congo, Democratic Republic of the",
        "prefix": "+243",
    },
    {"id": 85, "iso2": "CK", "iso3": "COK", "name_pl": "Wyspy Cooka", "name_en": "Cook Islands", "prefix": "+682"},
    {"id": 86, "iso2": "CR", "iso3": "CRI", "name_pl": "Kostaryka", "name_en": "Costa Rica", "prefix": "+506"},
    {
        "id": 87,
        "iso2": "CI",
        "iso3": "CIV",
        "name_pl": "Wybrzeże Kości Słoniowej",
        "name_en": "Côte d'Ivoire",
        "prefix": "+225",
    },
    {"id": 11, "iso2": "HR", "iso3": "HRV", "name_pl": "Chorwacja", "name_en": "Croatia", "prefix": "+385"},
    {"id": 89, "iso2": "CU", "iso3": "CUB", "name_pl": "Kuba", "name_en": "Cuba", "prefix": "+53"},
    {"id": 90, "iso2": "CW", "iso3": "CUW", "name_pl": "Curaçao", "name_en": "Curaçao", "prefix": "+599"},
    {"id": 13, "iso2": "CY", "iso3": "CYP", "name_pl": "Cypr", "name_en": "Cyprus", "prefix": "+357"},
    {"id": 3, "iso2": "CZ", "iso3": "CZE", "name_pl": "Czechy", "name_en": "Czechia", "prefix": "+420"},
    {"id": 4, "iso2": "DK", "iso3": "DNK", "name_pl": "Dania", "name_en": "Denmark", "prefix": "+45"},
    {"id": 94, "iso2": "DJ", "iso3": "DJI", "name_pl": "Dżibuti", "name_en": "Djibouti", "prefix": "+253"},
    {"id": 95, "iso2": "DM", "iso3": "DMA", "name_pl": "Dominika", "name_en": "Dominica", "prefix": "+1-767"},
    {
        "id": 96,
        "iso2": "DO",
        "iso3": "DOM",
        "name_pl": "Dominikana",
        "name_en": "Dominican Republic",
        "prefix": "+1-809, +1-829, +1-849",
    },
    {"id": 97, "iso2": "EC", "iso3": "ECU", "name_pl": "Ekwador", "name_en": "Ecuador", "prefix": "+593"},
    {"id": 98, "iso2": "EG", "iso3": "EGY", "name_pl": "Egipt", "name_en": "Egypt", "prefix": "+20"},
    {"id": 99, "iso2": "SV", "iso3": "SLV", "name_pl": "Salwador", "name_en": "El Salvador", "prefix": "+503"},
    {
        "id": 100,
        "iso2": "GQ",
        "iso3": "GNQ",
        "name_pl": "Gwinea Równikowa",
        "name_en": "Equatorial Guinea",
        "prefix": "+240",
    },
    {"id": 101, "iso2": "ER", "iso3": "ERI", "name_pl": "Erytrea", "name_en": "Eritrea", "prefix": "+291"},
    {"id": 6, "iso2": "EE", "iso3": "EST", "name_pl": "Estonia", "name_en": "Estonia", "prefix": "+372"},
    {"id": 103, "iso2": "ET", "iso3": "ETH", "name_pl": "Etiopia", "name_en": "Ethiopia", "prefix": "+251"},
    {
        "id": 104,
        "iso2": "FK",
        "iso3": "FLK",
        "name_pl": "Falklandy",
        "name_en": "Falkland Islands (Malvinas)",
        "prefix": "+500",
    },
    {"id": 105, "iso2": "FO", "iso3": "FRO", "name_pl": "Wyspy Owcze", "name_en": "Faroe Islands", "prefix": "+298"},
    {"id": 106, "iso2": "FJ", "iso3": "FJI", "name_pl": "Fidżi", "name_en": "Fiji", "prefix": "+679"},
    {"id": 26, "iso2": "FI", "iso3": "FIN", "name_pl": "Finlandia", "name_en": "Finland", "prefix": "+358"},
    {"id": 10, "iso2": "FR", "iso3": "FRA", "name_pl": "Francja", "name_en": "France", "prefix": "+33"},
    {
        "id": 109,
        "iso2": "GF",
        "iso3": "GUF",
        "name_pl": "Gujana Francuska",
        "name_en": "French Guiana",
        "prefix": "+594",
    },
    {
        "id": 110,
        "iso2": "PF",
        "iso3": "PYF",
        "name_pl": "Polinezja Francuska",
        "name_en": "French Polynesia",
        "prefix": "+689",
    },
    {
        "id": 111,
        "iso2": "TF",
        "iso3": "ATF",
        "name_pl": "Francuskie Terytoria Południowe i Antarktyczne",
        "name_en": "French Southern Territories",
        "prefix": "",
    },
    {"id": 112, "iso2": "GA", "iso3": "GAB", "name_pl": "Gabon", "name_en": "Gabon", "prefix": "+241"},
    {"id": 113, "iso2": "GM", "iso3": "GMB", "name_pl": "Gambia", "name_en": "Gambia", "prefix": "+220"},
    {"id": 114, "iso2": "GE", "iso3": "GEO", "name_pl": "Gruzja", "name_en": "Georgia", "prefix": "+995"},
    {"id": 5, "iso2": "DE", "iso3": "DEU", "name_pl": "Niemcy", "name_en": "Germany", "prefix": "+49"},
    {"id": 116, "iso2": "GH", "iso3": "GHA", "name_pl": "Ghana", "name_en": "Ghana", "prefix": "+233"},
    {"id": 117, "iso2": "GI", "iso3": "GIB", "name_pl": "Gibraltar", "name_en": "Gibraltar", "prefix": "+350"},
    {"id": 8, "iso2": "GR", "iso3": "GRC", "name_pl": "Grecja", "name_en": "Greece", "prefix": "+30"},
    {"id": 119, "iso2": "GL", "iso3": "GRL", "name_pl": "Grenlandia", "name_en": "Greenland", "prefix": "+299"},
    {"id": 120, "iso2": "GD", "iso3": "GRD", "name_pl": "Grenada", "name_en": "Grenada", "prefix": "+1-473"},
    {"id": 121, "iso2": "GP", "iso3": "GLP", "name_pl": "Gwadelupa", "name_en": "Guadeloupe", "prefix": "+590"},
    {"id": 122, "iso2": "GU", "iso3": "GUM", "name_pl": "Guam", "name_en": "Guam", "prefix": "+1-671"},
    {"id": 123, "iso2": "GT", "iso3": "GTM", "name_pl": "Gwatemala", "name_en": "Guatemala", "prefix": "+502"},
    {"id": 124, "iso2": "GG", "iso3": "GGY", "name_pl": "Guernsey", "name_en": "Guernsey", "prefix": "+44-1481"},
    {"id": 125, "iso2": "GN", "iso3": "GIN", "name_pl": "Gwinea", "name_en": "Guinea", "prefix": "+224"},
    {"id": 126, "iso2": "GW", "iso3": "GNB", "name_pl": "Gwinea Bissau", "name_en": "Guinea-Bissau", "prefix": "+245"},
    {"id": 127, "iso2": "GY", "iso3": "GUY", "name_pl": "Gujana", "name_en": "Guyana", "prefix": "+592"},
    {"id": 128, "iso2": "HT", "iso3": "HTI", "name_pl": "Haiti", "name_en": "Haiti", "prefix": "+509"},
    {
        "id": 129,
        "iso2": "HM",
        "iso3": "HMD",
        "name_pl": "Wyspy Heard i McDonalda",
        "name_en": "Heard Island and McDonald Islands",
        "prefix": "",
    },
    {"id": 130, "iso2": "VA", "iso3": "VAT", "name_pl": "Watykan", "name_en": "Holy See", "prefix": "+379"},
    {"id": 131, "iso2": "HN", "iso3": "HND", "name_pl": "Honduras", "name_en": "Honduras", "prefix": "+504"},
    {"id": 132, "iso2": "HK", "iso3": "HKG", "name_pl": "Hongkong", "name_en": "Hong Kong", "prefix": "+852"},
    {"id": 17, "iso2": "HU", "iso3": "HUN", "name_pl": "Węgry", "name_en": "Hungary", "prefix": "+36"},
    {"id": 32, "iso2": "IS", "iso3": "ISL", "name_pl": "Islandia", "name_en": "Iceland", "prefix": "+354"},
    {"id": 135, "iso2": "IN", "iso3": "IND", "name_pl": "Indie", "name_en": "India", "prefix": "+91"},
    {"id": 136, "iso2": "ID", "iso3": "IDN", "name_pl": "Indonezja", "name_en": "Indonesia", "prefix": "+62"},
    {
        "id": 137,
        "iso2": "IR",
        "iso3": "IRN",
        "name_pl": "Iran",
        "name_en": "Iran (Islamic Republic of)",
        "prefix": "+98",
    },
    {"id": 138, "iso2": "IQ", "iso3": "IRQ", "name_pl": "Irak", "name_en": "Iraq", "prefix": "+964"},
    {"id": 7, "iso2": "IE", "iso3": "IRL", "name_pl": "Irlandia", "name_en": "Ireland", "prefix": "+353"},
    {"id": 140, "iso2": "IM", "iso3": "IMN", "name_pl": "Wyspa Man", "name_en": "Isle of Man", "prefix": "+44-1624"},
    {"id": 141, "iso2": "IL", "iso3": "ISR", "name_pl": "Izrael", "name_en": "Israel", "prefix": "+972"},
    {"id": 12, "iso2": "IT", "iso3": "ITA", "name_pl": "Włochy", "name_en": "Italy", "prefix": "+39"},
    {"id": 143, "iso2": "JM", "iso3": "JAM", "name_pl": "Jamajka", "name_en": "Jamaica", "prefix": "+1-876"},
    {"id": 144, "iso2": "JP", "iso3": "JPN", "name_pl": "Japonia", "name_en": "Japan", "prefix": "+81"},
    {"id": 145, "iso2": "JE", "iso3": "JEY", "name_pl": "Jersey", "name_en": "Jersey", "prefix": "+44-1534"},
    {"id": 146, "iso2": "JO", "iso3": "JOR", "name_pl": "Jordania", "name_en": "Jordan", "prefix": "+962"},
    {"id": 147, "iso2": "KZ", "iso3": "KAZ", "name_pl": "Kazachstan", "name_en": "Kazakhstan", "prefix": "+7"},
    {"id": 148, "iso2": "KE", "iso3": "KEN", "name_pl": "Kenia", "name_en": "Kenya", "prefix": "+254"},
    {"id": 149, "iso2": "KI", "iso3": "KIR", "name_pl": "Kiribati", "name_en": "Kiribati", "prefix": "+686"},
    {
        "id": 150,
        "iso2": "KP",
        "iso3": "PRK",
        "name_pl": "Korea Północna",
        "name_en": "Korea (Democratic People's Republic of)",
        "prefix": "+850",
    },
    {
        "id": 151,
        "iso2": "KR",
        "iso3": "KOR",
        "name_pl": "Korea Południowa",
        "name_en": "Korea, Republic of",
        "prefix": "+82",
    },
    {"id": 152, "iso2": "KW", "iso3": "KWT", "name_pl": "Kuwejt", "name_en": "Kuwait", "prefix": "+965"},
    {"id": 153, "iso2": "KG", "iso3": "KGZ", "name_pl": "Kirgistan", "name_en": "Kyrgyzstan", "prefix": "+996"},
    {
        "id": 154,
        "iso2": "LA",
        "iso3": "LAO",
        "name_pl": "Laos",
        "name_en": "Lao People's Democratic Republic",
        "prefix": "+856",
    },
    {"id": 14, "iso2": "LV", "iso3": "LVA", "name_pl": "Łotwa", "name_en": "Latvia", "prefix": "+371"},
    {"id": 156, "iso2": "LB", "iso3": "LBN", "name_pl": "Liban", "name_en": "Lebanon", "prefix": "+961"},
    {"id": 157, "iso2": "LS", "iso3": "LSO", "name_pl": "Lesotho", "name_en": "Lesotho", "prefix": "+266"},
    {"id": 158, "iso2": "LR", "iso3": "LBR", "name_pl": "Liberia", "name_en": "Liberia", "prefix": "+231"},
    {"id": 159, "iso2": "LY", "iso3": "LBY", "name_pl": "Libia", "name_en": "Libya", "prefix": "+218"},
    {"id": 31, "iso2": "LI", "iso3": "LIE", "name_pl": "Liechtenstein", "name_en": "Liechtenstein", "prefix": "+423"},
    {"id": 15, "iso2": "LT", "iso3": "LTU", "name_pl": "Litwa", "name_en": "Lithuania", "prefix": "+370"},
    {"id": 16, "iso2": "LU", "iso3": "LUX", "name_pl": "Luksemburg", "name_en": "Luxembourg", "prefix": "+352"},
    {"id": 163, "iso2": "MO", "iso3": "MAC", "name_pl": "Makau", "name_en": "Macao", "prefix": "+853"},
    {
        "id": 164,
        "iso2": "MK",
        "iso3": "MKD",
        "name_pl": "Macedonia Północna",
        "name_en": "North Macedonia",
        "prefix": "+389",
    },
    {"id": 165, "iso2": "MG", "iso3": "MDG", "name_pl": "Madagaskar", "name_en": "Madagascar", "prefix": "+261"},
    {"id": 166, "iso2": "MW", "iso3": "MWI", "name_pl": "Malawi", "name_en": "Malawi", "prefix": "+265"},
    {"id": 167, "iso2": "MY", "iso3": "MYS", "name_pl": "Malezja", "name_en": "Malaysia", "prefix": "+60"},
    {"id": 168, "iso2": "MV", "iso3": "MDV", "name_pl": "Malediwy", "name_en": "Maldives", "prefix": "+960"},
    {"id": 169, "iso2": "ML", "iso3": "MLI", "name_pl": "Mali", "name_en": "Mali", "prefix": "+223"},
    {"id": 18, "iso2": "MT", "iso3": "MLT", "name_pl": "Malta", "name_en": "Malta", "prefix": "+356"},
    {
        "id": 171,
        "iso2": "MH",
        "iso3": "MHL",
        "name_pl": "Wyspy Marshalla",
        "name_en": "Marshall Islands",
        "prefix": "+692",
    },
    {"id": 172, "iso2": "MQ", "iso3": "MTQ", "name_pl": "Martynika", "name_en": "Martinique", "prefix": "+596"},
    {"id": 173, "iso2": "MR", "iso3": "MRT", "name_pl": "Mauretania", "name_en": "Mauritania", "prefix": "+222"},
    {"id": 174, "iso2": "MU", "iso3": "MUS", "name_pl": "Mauritius", "name_en": "Mauritius", "prefix": "+230"},
    {"id": 175, "iso2": "YT", "iso3": "MYT", "name_pl": "Majotta", "name_en": "Mayotte", "prefix": "+262"},
    {"id": 176, "iso2": "MX", "iso3": "MEX", "name_pl": "Meksyk", "name_en": "Mexico", "prefix": "+52"},
    {
        "id": 177,
        "iso2": "FM",
        "iso3": "FSM",
        "name_pl": "Mikronezja",
        "name_en": "Micronesia (Federated States of)",
        "prefix": "+691",
    },
    {"id": 178, "iso2": "MA", "iso3": "MAR", "name_pl": "Maroko", "name_en": "Morocco", "prefix": "+212"},
    {
        "id": 179,
        "iso2": "MD",
        "iso3": "MDA",
        "name_pl": "Mołdawia",
        "name_en": "Moldova, Republic of",
        "prefix": "+373",
    },
    {"id": 180, "iso2": "MC", "iso3": "MCO", "name_pl": "Monako", "name_en": "Monaco", "prefix": "+377"},
    {"id": 181, "iso2": "MN", "iso3": "MNG", "name_pl": "Mongolia", "name_en": "Mongolia", "prefix": "+976"},
    {"id": 182, "iso2": "ME", "iso3": "MNE", "name_pl": "Czarnogóra", "name_en": "Montenegro", "prefix": "+382"},
    {"id": 183, "iso2": "MS", "iso3": "MSR", "name_pl": "Montserrat", "name_en": "Montserrat", "prefix": "+1-664"},
    {"id": 184, "iso2": "MZ", "iso3": "MOZ", "name_pl": "Mozambik", "name_en": "Mozambique", "prefix": "+258"},
    {"id": 185, "iso2": "MM", "iso3": "MMR", "name_pl": "Mjanma", "name_en": "Myanmar", "prefix": "+95"},
    {"id": 186, "iso2": "NA", "iso3": "NAM", "name_pl": "Namibia", "name_en": "Namibia", "prefix": "+264"},
    {"id": 187, "iso2": "NR", "iso3": "NRU", "name_pl": "Nauru", "name_en": "Nauru", "prefix": "+674"},
    {"id": 188, "iso2": "NP", "iso3": "NPL", "name_pl": "Nepal", "name_en": "Nepal", "prefix": "+977"},
    {"id": 19, "iso2": "NL", "iso3": "NLD", "name_pl": "Holandia", "name_en": "Netherlands", "prefix": "+31"},
    {"id": 190, "iso2": "NC", "iso3": "NCL", "name_pl": "Nowa Kaledonia", "name_en": "New Caledonia", "prefix": "+687"},
    {"id": 191, "iso2": "NZ", "iso3": "NZL", "name_pl": "Nowa Zelandia", "name_en": "New Zealand", "prefix": "+64"},
    {"id": 192, "iso2": "NI", "iso3": "NIC", "name_pl": "Nikaragua", "name_en": "Nicaragua", "prefix": "+505"},
    {"id": 193, "iso2": "NE", "iso3": "NER", "name_pl": "Niger", "name_en": "Niger", "prefix": "+227"},
    {"id": 194, "iso2": "NG", "iso3": "NGA", "name_pl": "Nigeria", "name_en": "Nigeria", "prefix": "+234"},
    {"id": 195, "iso2": "NU", "iso3": "NIU", "name_pl": "Niue", "name_en": "Niue", "prefix": "+683"},
    {"id": 196, "iso2": "NF", "iso3": "NFK", "name_pl": "Norfolk", "name_en": "Norfolk Island", "prefix": "+672"},
    {
        "id": 197,
        "iso2": "MP",
        "iso3": "MNP",
        "name_pl": "Mariany Północne",
        "name_en": "Northern Mariana Islands",
        "prefix": "+1-670",
    },
    {"id": 29, "iso2": "NO", "iso3": "NOR", "name_pl": "Norwegia", "name_en": "Norway", "prefix": "+47"},
    {"id": 199, "iso2": "OM", "iso3": "OMN", "name_pl": "Oman", "name_en": "Oman", "prefix": "+968"},
    {"id": 200, "iso2": "PK", "iso3": "PAK", "name_pl": "Pakistan", "name_en": "Pakistan", "prefix": "+92"},
    {"id": 201, "iso2": "PW", "iso3": "PLW", "name_pl": "Palau", "name_en": "Palau", "prefix": "+680"},
    {
        "id": 202,
        "iso2": "PS",
        "iso3": "PSE",
        "name_pl": "Palestyna",
        "name_en": "Palestine, State of",
        "prefix": "+970",
    },
    {"id": 203, "iso2": "PA", "iso3": "PAN", "name_pl": "Panama", "name_en": "Panama", "prefix": "+507"},
    {
        "id": 204,
        "iso2": "PG",
        "iso3": "PNG",
        "name_pl": "Papua-Nowa Gwinea",
        "name_en": "Papua New Guinea",
        "prefix": "+675",
    },
    {"id": 205, "iso2": "PY", "iso3": "PRY", "name_pl": "Paragwaj", "name_en": "Paraguay", "prefix": "+595"},
    {"id": 206, "iso2": "PE", "iso3": "PER", "name_pl": "Peru", "name_en": "Peru", "prefix": "+51"},
    {"id": 207, "iso2": "PH", "iso3": "PHL", "name_pl": "Filipiny", "name_en": "Philippines", "prefix": "+63"},
    {"id": 208, "iso2": "PN", "iso3": "PCN", "name_pl": "Pitcairn", "name_en": "Pitcairn", "prefix": "+64"},
    {"id": 21, "iso2": "PL", "iso3": "POL", "name_pl": "Polska", "name_en": "Poland", "prefix": "+48"},
    {"id": 22, "iso2": "PT", "iso3": "PRT", "name_pl": "Portugalia", "name_en": "Portugal", "prefix": "+351"},
    {
        "id": 211,
        "iso2": "PR",
        "iso3": "PRI",
        "name_pl": "Portoryko",
        "name_en": "Puerto Rico",
        "prefix": "+1-787, +1-939",
    },
    {"id": 212, "iso2": "QA", "iso3": "QAT", "name_pl": "Katar", "name_en": "Qatar", "prefix": "+974"},
    {"id": 213, "iso2": "RE", "iso3": "REU", "name_pl": "Reunion", "name_en": "Réunion", "prefix": "+262"},
    {"id": 23, "iso2": "RO", "iso3": "ROU", "name_pl": "Rumunia", "name_en": "Romania", "prefix": "+40"},
    {"id": 215, "iso2": "RU", "iso3": "RUS", "name_pl": "Rosja", "name_en": "Russian Federation", "prefix": "+7"},
    {"id": 216, "iso2": "RW", "iso3": "RWA", "name_pl": "Rwanda", "name_en": "Rwanda", "prefix": "+250"},
    {
        "id": 217,
        "iso2": "BL",
        "iso3": "BLM",
        "name_pl": "Saint-Barthélemy",
        "name_en": "Saint Barthélemy",
        "prefix": "+590",
    },
    {
        "id": 218,
        "iso2": "SH",
        "iso3": "SHN",
        "name_pl": "Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha",
        "name_en": "Saint Helena, Ascension and Tristan da Cunha",
        "prefix": "+290",
    },
    {
        "id": 219,
        "iso2": "KN",
        "iso3": "KNA",
        "name_pl": "Saint Kitts i Nevis",
        "name_en": "Saint Kitts and Nevis",
        "prefix": "+1-869",
    },
    {"id": 220, "iso2": "LC", "iso3": "LCA", "name_pl": "Saint Lucia", "name_en": "Saint Lucia", "prefix": "+1-758"},
    {
        "id": 221,
        "iso2": "MF",
        "iso3": "MAF",
        "name_pl": "Saint-Martin",
        "name_en": "Saint Martin (French part)",
        "prefix": "+590",
    },
    {
        "id": 222,
        "iso2": "PM",
        "iso3": "SPM",
        "name_pl": "Saint-Pierre i Miquelon",
        "name_en": "Saint Pierre and Miquelon",
        "prefix": "+508",
    },
    {
        "id": 223,
        "iso2": "VC",
        "iso3": "VCT",
        "name_pl": "Saint Vincent i Grenadyny",
        "name_en": "Saint Vincent and the Grenadines",
        "prefix": "+1-784",
    },
    {"id": 224, "iso2": "WS", "iso3": "WSM", "name_pl": "Samoa", "name_en": "Samoa", "prefix": "+685"},
    {"id": 225, "iso2": "SM", "iso3": "SMR", "name_pl": "San Marino", "name_en": "San Marino", "prefix": "+378"},
    {
        "id": 226,
        "iso2": "ST",
        "iso3": "STP",
        "name_pl": "Wyspy Świętego Tomasza i Książęca",
        "name_en": "Sao Tome and Principe",
        "prefix": "+239",
    },
    {
        "id": 227,
        "iso2": "SA",
        "iso3": "SAU",
        "name_pl": "Arabia Saudyjska",
        "name_en": "Saudi Arabia",
        "prefix": "+966",
    },
    {"id": 228, "iso2": "SN", "iso3": "SEN", "name_pl": "Senegal", "name_en": "Senegal", "prefix": "+221"},
    {"id": 229, "iso2": "RS", "iso3": "SRB", "name_pl": "Serbia", "name_en": "Serbia", "prefix": "+381"},
    {"id": 230, "iso2": "SC", "iso3": "SYC", "name_pl": "Seszele", "name_en": "Seychelles", "prefix": "+248"},
    {"id": 231, "iso2": "SL", "iso3": "SLE", "name_pl": "Sierra Leone", "name_en": "Sierra Leone", "prefix": "+232"},
    {"id": 232, "iso2": "SG", "iso3": "SGP", "name_pl": "Singapur", "name_en": "Singapore", "prefix": "+65"},
    {
        "id": 233,
        "iso2": "SX",
        "iso3": "SXM",
        "name_pl": "Sint Maarten",
        "name_en": "Sint Maarten (Dutch part)",
        "prefix": "+1-721",
    },
    {"id": 25, "iso2": "SK", "iso3": "SVK", "name_pl": "Słowacja", "name_en": "Slovakia", "prefix": "+421"},
    {"id": 24, "iso2": "SI", "iso3": "SVN", "name_pl": "Słowenia", "name_en": "Slovenia", "prefix": "+386"},
    {
        "id": 236,
        "iso2": "SB",
        "iso3": "SLB",
        "name_pl": "Wyspy Salomona",
        "name_en": "Solomon Islands",
        "prefix": "+677",
    },
    {"id": 237, "iso2": "SO", "iso3": "SOM", "name_pl": "Somalia", "name_en": "Somalia", "prefix": "+252"},
    {
        "id": 238,
        "iso2": "ZA",
        "iso3": "ZAF",
        "name_pl": "Południowa Afryka",
        "name_en": "South Africa",
        "prefix": "+27",
    },
    {
        "id": 239,
        "iso2": "GS",
        "iso3": "SGS",
        "name_pl": "Georgia Południowa i Sandwich Południowy",
        "name_en": "South Georgia and the South Sandwich Islands",
        "prefix": "",
    },
    {"id": 240, "iso2": "SS", "iso3": "SSD", "name_pl": "Sudan Południowy", "name_en": "South Sudan", "prefix": "+211"},
    {"id": 9, "iso2": "ES", "iso3": "ESP", "name_pl": "Hiszpania", "name_en": "Spain", "prefix": "+34"},
    {"id": 242, "iso2": "LK", "iso3": "LKA", "name_pl": "Sri Lanka", "name_en": "Sri Lanka", "prefix": "+94"},
    {"id": 243, "iso2": "SD", "iso3": "SDN", "name_pl": "Sudan", "name_en": "Sudan", "prefix": "+249"},
    {"id": 244, "iso2": "SR", "iso3": "SUR", "name_pl": "Surinam", "name_en": "Suriname", "prefix": "+597"},
    {
        "id": 245,
        "iso2": "SJ",
        "iso3": "SJM",
        "name_pl": "Svalbard i Jan Mayen",
        "name_en": "Svalbard and Jan Mayen",
        "prefix": "+47",
    },
    {"id": 246, "iso2": "SZ", "iso3": "SWZ", "name_pl": "Eswatini", "name_en": "Eswatini", "prefix": "+268"},
    {"id": 27, "iso2": "SE", "iso3": "SWE", "name_pl": "Szwecja", "name_en": "Sweden", "prefix": "+46"},
    {"id": 30, "iso2": "CH", "iso3": "CHE", "name_pl": "Szwajcaria", "name_en": "Switzerland", "prefix": "+41"},
    {"id": 249, "iso2": "SY", "iso3": "SYR", "name_pl": "Syria", "name_en": "Syrian Arab Republic", "prefix": "+963"},
    {
        "id": 250,
        "iso2": "TW",
        "iso3": "TWN",
        "name_pl": "Tajwan",
        "name_en": "Taiwan, Province of China",
        "prefix": "+886",
    },
    {"id": 251, "iso2": "TJ", "iso3": "TJK", "name_pl": "Tadżykistan", "name_en": "Tajikistan", "prefix": "+992"},
    {
        "id": 252,
        "iso2": "TZ",
        "iso3": "TZA",
        "name_pl": "Tanzania",
        "name_en": "Tanzania, United Republic of",
        "prefix": "+255",
    },
    {"id": 253, "iso2": "TH", "iso3": "THA", "name_pl": "Tajlandia", "name_en": "Thailand", "prefix": "+66"},
    {"id": 254, "iso2": "TL", "iso3": "TLS", "name_pl": "Timor Wschodni", "name_en": "Timor-Leste", "prefix": "+670"},
    {"id": 255, "iso2": "TG", "iso3": "TGO", "name_pl": "Togo", "name_en": "Togo", "prefix": "+228"},
    {"id": 256, "iso2": "TK", "iso3": "TKL", "name_pl": "Tokelau", "name_en": "Tokelau", "prefix": "+690"},
    {"id": 257, "iso2": "TO", "iso3": "TON", "name_pl": "Tonga", "name_en": "Tonga", "prefix": "+676"},
    {
        "id": 258,
        "iso2": "TT",
        "iso3": "TTO",
        "name_pl": "Trynidad i Tobago",
        "name_en": "Trinidad and Tobago",
        "prefix": "+1-868",
    },
    {"id": 259, "iso2": "TN", "iso3": "TUN", "name_pl": "Tunezja", "name_en": "Tunisia", "prefix": "+216"},
    {"id": 260, "iso2": "TR", "iso3": "TUR", "name_pl": "Turcja", "name_en": "Türkiye", "prefix": "+90"},
    {"id": 261, "iso2": "TM", "iso3": "TKM", "name_pl": "Turkmenistan", "name_en": "Turkmenistan", "prefix": "+993"},
    {
        "id": 262,
        "iso2": "TC",
        "iso3": "TCA",
        "name_pl": "Turks i Caicos",
        "name_en": "Turks and Caicos Islands",
        "prefix": "+1-649",
    },
    {"id": 263, "iso2": "TV", "iso3": "TUV", "name_pl": "Tuvalu", "name_en": "Tuvalu", "prefix": "+688"},
    {"id": 264, "iso2": "UG", "iso3": "UGA", "name_pl": "Uganda", "name_en": "Uganda", "prefix": "+256"},
    {"id": 265, "iso2": "UA", "iso3": "UKR", "name_pl": "Ukraina", "name_en": "Ukraine", "prefix": "+380"},
    {
        "id": 266,
        "iso2": "AE",
        "iso3": "ARE",
        "name_pl": "Zjednoczone Emiraty Arabskie",
        "name_en": "United Arab Emirates",
        "prefix": "+971",
    },
    {
        "id": 28,
        "iso2": "GB",
        "iso3": "GBR",
        "name_pl": "Wielka Brytania",
        "name_en": "United Kingdom of Great Britain and Northern Ireland",
        "prefix": "+44",
    },
    {
        "id": 268,
        "iso2": "US",
        "iso3": "USA",
        "name_pl": "Stany Zjednoczone",
        "name_en": "United States of America",
        "prefix": "+1",
    },
    {
        "id": 269,
        "iso2": "UM",
        "iso3": "UMI",
        "name_pl": "Dalekie Wyspy Mniejsze Stanów Zjednoczonych",
        "name_en": "United States Minor Outlying Islands",
        "prefix": "",
    },
    {"id": 270, "iso2": "UY", "iso3": "URY", "name_pl": "Urugwaj", "name_en": "Uruguay", "prefix": "+598"},
    {"id": 271, "iso2": "UZ", "iso3": "UZB", "name_pl": "Uzbekistan", "name_en": "Uzbekistan", "prefix": "+998"},
    {"id": 272, "iso2": "VU", "iso3": "VUT", "name_pl": "Vanuatu", "name_en": "Vanuatu", "prefix": "+678"},
    {
        "id": 273,
        "iso2": "VE",
        "iso3": "VEN",
        "name_pl": "Wenezuela",
        "name_en": "Venezuela (Bolivarian Republic of)",
        "prefix": "+58",
    },
    {"id": 274, "iso2": "VN", "iso3": "VNM", "name_pl": "Wietnam", "name_en": "Viet Nam", "prefix": "+84"},
    {
        "id": 275,
        "iso2": "VG",
        "iso3": "VGB",
        "name_pl": "Brytyjskie Wyspy Dziewicze",
        "name_en": "Virgin Islands (British)",
        "prefix": "+1-284",
    },
    {
        "id": 276,
        "iso2": "VI",
        "iso3": "VIR",
        "name_pl": "Wyspy Dziewicze Stanów Zjednoczonych",
        "name_en": "Virgin Islands (U.S.)",
        "prefix": "+1-340",
    },
    {
        "id": 277,
        "iso2": "WF",
        "iso3": "WLF",
        "name_pl": "Wallis i Futuna",
        "name_en": "Wallis and Futuna",
        "prefix": "+681",
    },
    {
        "id": 278,
        "iso2": "EH",
        "iso3": "ESH",
        "name_pl": "Sahara Zachodnia",
        "name_en": "Western Sahara",
        "prefix": "+212",
    },
    {"id": 279, "iso2": "YE", "iso3": "YEM", "name_pl": "Jemen", "name_en": "Yemen", "prefix": "+967"},
    {"id": 280, "iso2": "ZM", "iso3": "ZMB", "name_pl": "Zambia", "name_en": "Zambia", "prefix": "+260"},
    {"id": 281, "iso2": "ZW", "iso3": "ZWE", "name_pl": "Zimbabwe", "name_en": "Zimbabwe", "prefix": "+263"},
]

extra_countries = [
    {
        "id": 28,
        "iso2": "GB",
        "iso3": "GBR",
        "name_pl": "Wielka Brytania",
        "name_en": "United Kingdom of Great Britain",
        "prefix": "+44",
    },
    {
        "id": 282,
        "iso2": "XI",
        "iso3": "XNI",
        "name_pl": "Irlandia Północna",
        "name_en": "Northern Ireland",
        "prefix": "+44",
    },
    {"id": 283, "iso2": "XK", "iso3": "XKK", "name_pl": "Kosowo", "name_en": "Kosovo", "prefix": "+383"},
]

currencies_symbols = [
    {"id": 1, "iso3": "PLN", "symbol": "zł"},
    {"id": 2, "iso3": "USD", "symbol": "$"},
    {"id": 3, "iso3": "EUR", "symbol": "€"},
    {"id": 4, "iso3": "GBP", "symbol": "£"},
    {"id": 5, "iso3": "CNY", "symbol": "¥"},
    {"id": 6, "iso3": "SEK", "symbol": "kr"},
]


def _upsert_countries(apps, rows):
    Country = apps.get_model("django_regional", "Country")
    for country in rows:
        Country.objects.update_or_create(
            id=country["id"],
            defaults={
                "iso2": country["iso2"].upper(),
                "iso3": country["iso3"].upper(),
                "name_pl": country["name_pl"],
                "name_en": country["name_en"],
                "prefix": country["prefix"],
            },
        )


def seed_countries(apps, schema_editor):
    _upsert_countries(apps, countries)


def seed_extra_countries(apps, schema_editor):
    _upsert_countries(apps, extra_countries)


def seed_currency_symbols(apps, schema_editor):
    Currency = apps.get_model("django_regional", "Currency")
    for currency in currencies_symbols:
        Currency.objects.update_or_create(
            id=currency["id"],
            defaults={
                "iso3": currency["iso3"].upper(),
                "symbol": currency["symbol"],
            },
        )


def fill_country_default_currency(apps, schema_editor):
    Country = apps.get_model("django_regional", "Country")
    Currency = apps.get_model("django_regional", "Currency")
    for country in Country.objects.all():
        if country.default_currency is None:
            if country.iso2 == "PL":
                country.default_currency = Currency.objects.get(iso3="PLN")
            elif country.iso2 in ["GB", "XI"]:
                country.default_currency = Currency.objects.get(iso3="GBP")
            elif country.iso2 in ["US", "CA"]:
                country.default_currency = Currency.objects.get(iso3="USD")
            else:
                country.default_currency = Currency.objects.get(iso3="EUR")

            country.save()


class Migration(migrations.Migration):
    initial = True

    # Squash of the full 0001-0006 chain. Existing databases that already ran the
    # original chain are marked as applied via `replaces`; fresh installs run this
    # single migration. 0002's prefix fill is intentionally not replayed: on a fresh
    # database the Country table is empty at that point (data arrives with the 0003
    # payload below, prefixes included).
    replaces = [
        ("django_regional", "0001_initial"),
        ("django_regional", "0002_country_prefix"),
        ("django_regional", "0003_alter_country_name_en_alter_country_name_pl"),
        ("django_regional", "0004_currency_symbol"),
        ("django_regional", "0005_add_new_countries"),
        ("django_regional", "0006_country_default_currency"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("iso3", models.CharField(max_length=3, unique=True)),
                ("name_en", models.CharField(max_length=24)),
                ("name_pl", models.CharField(max_length=24)),
                ("symbol", models.CharField(default="", max_length=16)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "ordering": ["iso3"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("iso2", models.CharField(max_length=2, unique=True)),
                ("iso3", models.CharField(max_length=3, unique=True)),
                ("name_en", models.CharField(max_length=16)),
                ("name_pl", models.CharField(max_length=16)),
                ("name_source", models.CharField(default="", max_length=16)),
            ],
            options={
                "verbose_name_plural": "languages",
                "ordering": ["name_pl"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("iso2", models.CharField(max_length=2)),
                ("iso3", models.CharField(max_length=3)),
                ("name_en", models.CharField(max_length=100)),
                ("name_pl", models.CharField(max_length=100)),
                ("prefix", models.CharField(default="", max_length=32)),
                (
                    "default_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_regional.currency",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ["iso3"],
                "constraints": [
                    models.UniqueConstraint(django.db.models.functions.text.Lower("iso2"), name="country_unique_iso2"),
                    models.UniqueConstraint(django.db.models.functions.text.Lower("iso3"), name="country_unique_iso3"),
                ],
            },
        ),
        migrations.RunPython(seed_countries, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(seed_currency_symbols, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(seed_extra_countries, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(fill_country_default_currency, reverse_code=migrations.RunPython.noop),
    ]
